#!/bin/bash
# =============================================================================
# migrate_to_shared.sh — Consolidate fragmented workspaces into unified SHARED
# =============================================================================
# This script:
#   1. Creates SHARED/ directory structure
#   2. Consolidates ALL research_log.md files into one
#   3. Moves ALL strategies into SHARED/strategies/
#   4. Moves ALL backtests into SHARED/backtests/
#   5. Creates symlinks from each workspace to shared files
#   6. Backs up before doing anything destructive
# =============================================================================

set -euo pipefail

OPENCLAW="/Users/lich/.openclaw"
BACKUP_DIR="$OPENCLAW/backups/migration_$(date +%Y%m%d_%H%M%S)"
TIMESTAMP=$(date +%Y-%m-%d\ %H:%M:%S)

echo "=============================================="
echo "  WORKSPACE CONSOLIDATION MIGRATION"
echo "  Started: $TIMESTAMP"
echo "=============================================="
echo ""

# =============================================================================
# STEP 0: Create backup of current state
# =============================================================================
echo "📦 STEP 0: Creating backup..."
mkdir -p "$BACKUP_DIR"
cp -r "$OPENCLAW/workspace" "$BACKUP_DIR/" 2>/dev/null || true
cp -r "$OPENCLAW/workspace-coder" "$BACKUP_DIR/" 2>/dev/null || true
cp -r "$OPENCLAW/workspace-backtester" "$BACKUP_DIR/" 2>/dev/null || true
cp -r "$OPENCLAW/workspace-alpha-hunter" "$BACKUP_DIR/" 2>/dev/null || true
cp -r "$OPENCLAW/workspace-allocator" "$BACKUP_DIR/" 2>/dev/null || true
cp -r "$OPENCLAW/shared" "$BACKUP_DIR/" 2>/dev/null || true
echo "   ✅ Backup created at: $BACKUP_DIR"
echo ""

# =============================================================================
# STEP 1: Create SHARED/ directory structure
# =============================================================================
echo "📁 STEP 1: Creating SHARED/ directory structure..."

SHARED="$OPENCLAW/SHARED"
mkdir -p "$SHARED"/{strategies,backtests,research,memory,agents}

# Create a marker file
cat > "$SHARED/README.md" << 'EOF'
# SHARED/ — Unified Workspace for All Agents

This directory is the **single source of truth** for all agents.

## Structure
```
SHARED/
├── research/           # Research logs (ONE research_log.md)
├── strategies/         # All strategy code
├── backtests/         # All backtest results
├── memory/            # Shared memory and learnings
└── agents/           # Agent-specific shared configs
```

## How It Works
- Each workspace has its own SOUL.md/IDENTITY.md for context isolation
- But ALL workspaces symlink to these shared files for coordination
- No more "coder doesn't know what backtester is doing"
EOF

echo "   ✅ Created: $SHARED/"
echo ""

# =============================================================================
# STEP 2: Consolidate ALL research_log.md files
# =============================================================================
echo "📝 STEP 2: Consolidating research_log.md files..."

# Collect all research logs with their sources
RESEARCH_LOG="$SHARED/research/research_log.md"
mkdir -p "$SHARED/research"

# Start new consolidated log
cat > "$RESEARCH_LOG" << 'HEADER'
# SHARED Research Log — Unified Pipeline Tracking

> ⚠️  This is the **SINGLE source of truth** for ALL strategies across ALL workspaces.
> Generated by consolidation script on $(date +%Y-%m-%d)

---

## Master Dashboard
HEADER

# Function to extract dashboard from a research log
extract_dashboard() {
    local file="$1"
    local source="$2"
    if [[ -f "$file" ]]; then
        echo ""
        echo "### From: $source"
        grep -A 20 "## Master Dashboard\|## Dashboard" "$file" 2>/dev/null || echo "(no dashboard found)"
    fi
}

# Extract dashboards from all known research logs
extract_dashboard "$OPENCLAW/workspace/research_log.md" "workspace/"
extract_dashboard "$OPENCLAW/workspace-coder/research_log.md" "workspace-coder/"
extract_dashboard "$OPENCLAW/workspace-alpha-hunter/research_log.md" "workspace-alpha-hunter/"
extract_dashboard "$OPENCLAW/shared/research_log.md" "shared/"

cat >> "$RESEARCH_LOG" << 'HEADER'

---

## Complete Pipeline History

### Original Workspaces Consolidated:
1. workspace/ — Main orchestrator workspace
2. workspace-coder/ — Strategy coding workspace
3. workspace-backtester/ — Backtesting workspace
4. workspace-alpha-hunter/ — Research/alpha hunting workspace
5. shared/ — Previously shared directory

All strategies from these workspaces are now unified below.
HEADER

echo "   ✅ Consolidated research_log.md created"
echo ""

# =============================================================================
# STEP 3: Move ALL strategies into SHARED/strategies/
# =============================================================================
echo "📊 STEP 3: Consolidating strategies..."

STRATEGIES="$SHARED/strategies"
mkdir -p "$STRATEGIES"

# Copy strategies from main workspace
if [[ -d "$OPENCLAW/workspace/strategies" ]]; then
    cp -n "$OPENCLAW/workspace/strategies"/*.py "$STRATEGIES/" 2>/dev/null || true
    echo "   ✅ Copied from workspace/strategies/"
fi

# Copy strategies from coder workspace
if [[ -d "$OPENCLAW/workspace-coder/strategies" ]]; then
    cp -n "$OPENCLAW/workspace-coder/strategies"/*.py "$STRATEGIES/" 2>/dev/null || true
    echo "   ✅ Copied from workspace-coder/strategies/"
fi

# Copy strategies from backtester workspace
if [[ -d "$OPENCLAW/workspace-backtester/strategies" ]]; then
    cp -n "$OPENCLAW/workspace-backtester/strategies"/*.py "$STRATEGIES/" 2>/dev/null || true
    echo "   ✅ Copied from workspace-backtester/strategies/"
fi

# Remove duplicates (prefer newer files based on modification time)
cd "$STRATEGIES"
for f in *.py; do
    [[ -f "$f" ]] || continue
    # Find all copies across workspaces
    COPIES=$(find "$OPENCLAW" -name "$f" -type f 2>/dev/null)
    if echo "$COPIES" | grep -q "workspace-coder"; then
        # Prefer coder version if exists
        cp "$OPENCLAW/workspace-coder/strategies/$f" "$f" 2>/dev/null || true
    fi
done

# Create index of all strategies
cat > "$STRATEGIES/README.md" << 'EOF'
# Strategy Registry

All strategy code is stored here. Naming convention:
```
{type}_{instrument}_{timeframe}.py

trend_btcusd_h4.py      ← Trend strategy on BTC/USD H4
meanrev_eurusd_d.py     ← Mean reversion on EUR/USD Daily
```

## Index
EOF

ls -1 "$STRATEGIES"/*.py 2>/dev/null | while read f; do
    basename "$f" | sed 's/^/- `/' | sed 's/$/`/' >> "$STRATEGIES/README.md"
done

echo "   📈 Total strategies: $(ls -1 "$STRATEGIES"/*.py 2>/dev/null | wc -l | tr -d ' ')"
echo ""

# =============================================================================
# STEP 4: Move ALL backtests into SHARED/backtests/
# =============================================================================
echo "📉 STEP 4: Consolidating backtests..."

BACKTESTS="$SHARED/backtests"
mkdir -p "$BACKTESTS"

# Copy from main workspace
if [[ -d "$OPENCLAW/workspace/backtests" ]]; then
    cp -n "$OPENCLAW/workspace/backtests"/*.json "$BACKTESTS/" 2>/dev/null || true
    cp -n "$OPENCLAW/workspace/backtests"/*.csv "$BACKTESTS/" 2>/dev/null || true
    echo "   ✅ Copied from workspace/backtests/"
fi

# Copy from allocator workspace
if [[ -d "$OPENCLAW/workspace-allocator/backtest_results" ]]; then
    cp -n "$OPENCLAW/workspace-allocator/backtest_results"/* "$BACKTESTS/" 2>/dev/null || true
    echo "   ✅ Copied from workspace-allocator/backtest_results/"
fi

echo "   📊 Total backtest files: $(ls -1 "$BACKTESTS" 2>/dev/null | wc -l | tr -d ' ')"
echo ""

# =============================================================================
# STEP 5: Create symlinks from each workspace to shared files
# =============================================================================
echo "🔗 STEP 5: Creating symlinks..."

WORKSPACES=(
    "workspace"
    "workspace-coder"
    "workspace-backtester"
    "workspace-alpha-hunter"
    "workspace-allocator"
    "workspace-executioner"
)

for ws in "${WORKSPACES[@]}"; do
    WS_DIR="$OPENCLAW/$ws"
    [[ -d "$WS_DIR" ]] || continue
    
    echo "   Processing $ws..."
    
    # Remove existing research_log.md (will replace with symlink)
    if [[ -f "$WS_DIR/research_log.md" ]] && [[ ! -L "$WS_DIR/research_log.md" ]]; then
        mv "$WS_DIR/research_log.md" "$WS_DIR/research_log.md.bak_$(date +%s)" 2>/dev/null || true
    fi
    
    # Create symlink to shared research_log
    ln -sf "$SHARED/research/research_log.md" "$WS_DIR/research_log.md" 2>/dev/null || true
    
    # For workspaces that have strategies/ folder, symlink to shared
    if [[ -d "$WS_DIR/strategies" ]] && [[ ! -L "$WS_DIR/strategies" ]]; then
        mv "$WS_DIR/strategies" "$WS_DIR/strategies.local_$(date +%s)" 2>/dev/null || true
    fi
    ln -sf "$SHARED/strategies" "$WS_DIR/strategies" 2>/dev/null || true
done

echo "   ✅ Symlinks created"
echo ""

# =============================================================================
# STEP 6: Create unified MEMORY.md in SHARED
# =============================================================================
echo "🧠 STEP 6: Creating shared MEMORY.md..."

cat > "$SHARED/memory/MEMORY.md" << 'EOF'
# SHARED Memory — Cross-Agent Institutional Knowledge

> All agents contribute to this memory. This is what "institutional knowledge" looks like.

## Key Learnings

### What Works
- Kelly weighting over uniform risk allocation (Sharpe improvement: 1.546 → 2.032)
- Daily timeframe consistently outperforms H4 across strategies
- Mean reversion fails on H4 due to costs; only trend-following survives
- Portfolio naturally diversifies: avg 2.25 concurrent positions

### What Doesn't Work
- Overly complex strategies with >4 indicators (overfitting)
- Pure mean reversion without trend filter on H4
- Insufficient sample size (<50 trades) for validation

### Strategy Categories That Work
1. Trend-following on Daily timeframe
2. Volatility expansion on H4
3. Regime-based switching (HMM/ADX)
4. Supertrend variants with volume confirmation

## Validated Strategies (Production Ready)
EOF

# Append validated strategies from main memory
if [[ -f "$OPENCLAW/workspace/MEMORY.md" ]]; then
    grep -A 30 "## Current State\|Live Positions\|Key Decisions" "$OPENCLAW/workspace/MEMORY.md" >> "$SHARED/memory/MEMORY.md" 2>/dev/null || true
fi

# Symlink MEMORY.md in main workspace
if [[ -f "$OPENCLAW/workspace/MEMORY.md" ]] && [[ ! -L "$OPENCLAW/workspace/MEMORY.md" ]]; then
    mv "$OPENCLAW/workspace/MEMORY.md" "$OPENCLAW/workspace/MEMORY.md.bak_$(date +%s)" 2>/dev/null || true
fi
ln -sf "$SHARED/memory/MEMORY.md" "$OPENCLAW/workspace/MEMORY.md" 2>/dev/null || true

echo "   ✅ Shared MEMORY.md created"
echo ""

# =============================================================================
# STEP 7: Summary
# =============================================================================
echo "=============================================="
echo "  ✅ MIGRATION COMPLETE"
echo "=============================================="
echo ""
echo "📁 SHARED/ created at: $OPENCLAW/SHARED/"
echo ""
echo "Contents:"
echo "  ├── research/         — Unified research_log.md"
echo "  ├── strategies/       — All strategy code ($(ls -1 $STRATEGIES/*.py 2>/dev/null | wc -l | tr -d ' ') files)"
echo "  ├── backtests/       — All backtest results"
echo "  ├── memory/           — Shared MEMORY.md"
echo "  └── agents/           — Agent configs"
echo ""
echo "🔗 Symlinks created in:"
for ws in "${WORKSPACES[@]}"; do
    [[ -d "$OPENCLAW/$ws" ]] && echo "   - $ws/"
done
echo ""
echo "💾 Backup saved at: $BACKUP_DIR"
echo ""
echo "⚠️  NEXT STEPS:"
echo "   1. Verify all symlinks work: ls -la {workspace}/research_log.md"
echo "   2. Test that agents can read the shared research_log.md"
echo "   3. Update agent SOUL.md files to reference SHARED paths"
echo "   4. Commit changes: cd $OPENCLAW && git add -A && git commit -m 'Consolidate to SHARED/'"
echo ""
